---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k0sdata
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dbstorageclass
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /var/export/vol1 
    server: 192.168.0.5
