---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgrespvc
spec:
  storageClassName: dbstorageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
      
